name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    environment: production-notarize-environment
    strategy:
      matrix:
        os: [macos-12]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install wine
        run: |
          brew install --cask wine-stable

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 18
          cache: 'npm'

      - name: Install python setup tools
        run: |
          pip install setuptools

      - name: Install dependencies
        run: |
          npm install

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}

          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EP_GH_IGNORE_TIME: true
        run: |
          npm run build
          npm exec electron-builder -- --publish always --win --mac --linux
